### ISSUE TITLE
non-differentiable error for code that needn't be differentiable

### ISSUE THREAD

**Issue by zenna** [FluxML/Zygote.jl#175]
The following snippet yields the error `ERROR: Non-differentiable function checked_sdiv_int` due to the `divrem`

```julia
x = rand(10)
grads = gradient(Params([x])) do
  a, b = divrem(3,5)
  c = a + 0.5
  sum(c .+ x)
end
```

Of course `divrem` is not a differentiable function but it shouldn't need to be.  In this case, the above example  is equivalent to:

```julia
x = rand(10)
grads = gradient(Params([x])) do
  a, b = 0,3
  c = a + 0.5
  sum(c .+ x)
end
```

which works just fine.

Is this known and/or expected?

**Comment by MikeInnes** [comment]
We just need to add a `@nograd divrem` to `number.jl`.

The fact that we differentiate `divrem` at all might be surprising; for context, the reason is that we don't know that `divrem` is pure, and if it modifies mutable state it could be relevant for differentiation. So rather than assuming it's pure we just run the Zygote transform on it and then let it compile away afterwards.

**Comment by zenna** [comment]
I see, thanks

**Comment by baggepinnen** [comment]
There should be a way to, in user code, opt out of differentiation of some expressions. `dropgrad` does not always seem to be smart enough. Example :

How can I opt out of taking grads of the push! expression here. The lossvec is only used for logging. @nograd or dropgrad do not seem to work. Do I have to define a new push! function and mark it as @nograd?
```
 function loss(model, x)
     l = sum(abs2.(model(x)))
     push!(lossvec, l)
     l
 end
```
Using tracker, I just pushed `l.data` and that effectively dropped all gradient.

**Comment by MikeInnes** [comment]
You can define a construct like:

```julia
ignore() do
  # push! etc
end
```

with

```julia
ignore(f) = f()
@adjoint ignore(f) = f(), _ -> nothing
```

Perhaps worth adding to Zygote proper, or at least worth documenting the pattern.

**Comment by baggepinnen** [comment]
Yeah, that would be a nice to have! Would it also take care of 
```
@warn "some text"
ERROR: try/catch not supported
```
?

**Comment by dhairyagandhi96** [comment]
In this construct I don't think you can do any compute that you do want the gradient for. Correct me if I'm wrong here?

**Comment by MikeInnes** [comment]
Right, it's explicitly dropping gradients. So it's a solution for things that currently error which should be ignored, but it doesn't fix anything that should be differentiable.

**Comment by ToucheSir** [comment]
The original issue is no longer one and the ignore utility mentioned has been in Zygote for some time now, so I think the final word on this has been said.
